# Generated by Django 4.2.2 on 2023-07-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_name', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
