# Generated by Django 4.2.2 on 2023-07-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_topic_service_host_message_service_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
