# Generated by Django 4.2.2 on 2023-07-04 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_service_options_service_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
