# Generated by Django 4.2.2 on 2023-07-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_service_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('email', models.TextField()),
                ('conNo', models.IntegerField()),
                ('nic', models.IntegerField()),
                ('paasword', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
