# Generated by Django 4.2.2 on 2023-07-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_customerapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerapi',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
