# Generated by Django 4.2.2 on 2023-07-07 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_customervalues_delete_customerapi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customervalues',
            old_name='paasword',
            new_name='password',
        ),
    ]
