# Generated by Django 4.2.2 on 2023-07-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_rename_paasword_customervalues_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Version', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=255)),
                ('Fuel', models.CharField(max_length=255)),
                ('Passengers', models.IntegerField()),
                ('Transmission', models.CharField(max_length=255)),
                ('Colour', models.CharField(max_length=255)),
                ('Rent_duration', models.CharField(max_length=255)),
                ('Amount', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Price_ExtraKm', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
