# Generated by Django 4.2.2 on 2023-07-09 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_cardetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetails',
            name='NumOfCar',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
