# Generated by Django 4.2.2 on 2023-07-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_cardetails_numofcar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='NumOfCar',
            field=models.CharField(max_length=255),
        ),
    ]
